# Generated by Django 3.2 on 2021-04-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20210415_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qa',
        ),
    ]
